# Ansible Playbook : deploy.yaml

---
- name: "Apache installation avec docker"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: "egeorges*1"
  pre_tasks:
    - name: INSTALL DEPENDANCES DOCKER
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      tags: docker

    - name: AJOUT CLE GPG DE DOCKER
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker

    - name: AJOUT DEPOT APT DE DOCKER
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
      tags: docker

    - name: INSTALL DOCKER
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags: docker

  tasks:
    - name: INSTALL DOCKER
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags: docker

    - name: DEMARRE DOCKER
      ansible.builtin.systemd_service:
        state: started
        name: docker
      tags: docker

 # tasks:
    - name: CREATE DOCKER CONTAINER FOR APACHE
      community.docker.docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        tags: webapp
